### ISSUE TITLE
Newbie experience

### ISSUE THREAD

**Issue by Santiquesada** [DBraun/ChucKDesigner#17]
Hello. Iam new in this world of Chuckdesigner, i am trying to learn. I am really good at Chuck, but I have not been able to run Chuckdesigner. My project just has one object and i am trying to add code on it. When i click on add code, or any other from the menu. it immediately crashes TD. See below images
![ChuckObject](https://github.com/DBraun/ChucKDesigner/assets/107777758/56c2f51a-e68a-4614-bc55-0b2a824fe9b4)
![Chuck error](https://github.com/DBraun/ChucKDesigner/assets/107777758/0a8ab613-023c-4aea-9a18-f411521d3bbb)

**Comment by DBraun** [comment]
Thanks. You've found a bug in which if the "Code" parameter is blank but you press "Add ChucK Code" then TouchDesigner crashes. I'll fix this in the next release. In the meantime, can you try specifying a DAT for the Code parameter? Watch the ChucKDesigner YouTube videos too if you haven't already.

**Comment by Santiquesada** [comment]
Great, now it is not crashing, but it is not producing any sound. is there any setup i am not doing?¿

![Screenshot 2024-02-17 210238](https://github.com/DBraun/ChucKDesigner/assets/107777758/2ac0adf8-60d9-4219-a134-e746d496be33)

**Comment by DBraun** [comment]
Great. I've made a new release with the bug fix: https://github.com/DBraun/ChucKDesigner/releases

To hear the audio in TouchDesigner you'll have to connect the ChucK Audio CHOP to an [Audio Device Out CHOP](https://docs.derivative.ca/Audio_Device_Out_CHOP). Try just a sine tone:

```chuck
// This constructor syntax is newly available in ChucK/ChucKDesigner!
SinOsc s(440) => dac;
while (true) {
    10::ms => now;
}
```

**Comment by Santiquesada** [comment]
Great it is working perfectly. Two final questions, and sorry if are very basic information, but anyways I think it will be very useful for new users in TD
1) in your videos you can see the messages in the console. how you make it? i also see that you run kind of a "perform mode", dont know how to make it.

2)what about those chuck files that need other chuck files that contain public classes or functions to run? how do you connect them. Lets suppose I have a ck code called Rock, but it needs the public class BPM that is in another file and needs to be running before i run Rock.ck

**Comment by Santiquesada** [comment]
Great it is working perfectly. Two final questions, and sorry if are very basic information, but anyways I think it will be very useful for new users in TD
1) in your videos you can see the messages in the console. how you make it? i also see that you run kind of a "perform mode", dont know how to make it.

my perform Mode is totally black, a completely different interface than yours in the video



2)what about those chuck files that need other chuck files that contain public classes or functions to run? how do you connect them. Lets suppose I have a ck code called Rock, but it needs the public class BPM that is in another file and needs to be running before i run Rock.ck


![Perform mode black screen](https://github.com/DBraun/ChucKDesigner/assets/107777758/b606d305-889c-4ea1-a7db-996eafb60472)

**Comment by Santiquesada** [comment]
Hello. Thanks for your reply. Sorry, Probably i did not explain myself very well. I understand the "importing classes" in Chuck, But i have been struggling in TD, cos of the different elements. 
You taught me that if " To hear the audio in TouchDesigner you'll have to connect the ChucK Audio CHOP to an [Audio Device Out CHOP" and It worked perfectly. My question is about those Chuck codes that dont have an audio output, like classes or functions. At what element should I connect them to run?

**Comment by DBraun** [comment]
Sorry I still don't fully understand. You should think of single ChucK Audio CHOP as a single version of miniAudicle. It's ok to add multiple shreds to the same ChucK Audio, and one shred can automatically add others via `Machine.add(...)`.

In the past I've borrowed from this example: https://github.com/ccrma/chuck/blob/main/examples/book/digital-artists/chapter9/initialize.ck

You only need to add the `initialize.ck` shred. Inside it allows `UseBPM.ck` to refer to a BPM class.

**Comment by Santiquesada** [comment]
Now I uderstood. I did not know each object was a single versión of miniAudicle. It Will work perfectly. Thanks for all your support
